name: NodeJS with Next.js Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DATABASE_URL: "postgresql://ci:ci@localhost:5432/ci_db?schema=public"
      DATABASE_URL_UNPOOLED: "postgresql://ci:ci@localhost:5432/ci_db?schema=public"
      NEXTAUTH_SECRET: "ci-secret-placeholder-32-chars-min"
      NEXTAUTH_URL: "http://localhost:3000"

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Build Next.js
        run: npm run build
